version: '3.8'
services:
    backend:
        # specify custom Dockerfile: Dockerfile.backend
        build:
            context: ./backend
            dockerfile: Dockerfile.backend
        ports:
            - "8000:8000"
        # environment:
        #     - OPENAI_API_KEY=${OPENAI_API_KEY}
        #     - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
        #     - OLLAMA_API_BASE=http://host.docker.internal:11434
        env_file:
            - ./backend/.env
    frontend:
        # specify custom Dockerfile: Dockerfile.frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile.frontend
        ports:
            - "5173:5173"
        depends_on:
            - backend