FROM python:3.13-slim
WORKDIR /app
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ./ .
# main.py:
# ---
# import uvicorn
# from dotenv import load_dotenv

# # Load environment variables
# load_dotenv()

# if __name__ == "__main__":
#     uvicorn.run("psl.api:app", host="0.0.0.0", port=8000, reload=True)
# ---
EXPOSE 8000



CMD ["python", "main.py"]